apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-hingle2.0
spec:
  displayName: Hingle2.0
  author:
    name: Dujing
    website: https://blog.dujing.space
  description: 基于halo-theme-hingle2.0的魔改主题
  logo: http://cdn.sep.cc/avatar/e2d1f9c5da125994d7bf02c691e3124a?s=256&d=identicon
  homepage: https://github.com/lixiaowanggit/halo-theme-hingle2.0
  repo: https://github.com/lixiaowanggit/halo-theme-hingle2.0.git
  settingName: "theme-Hingle-setting"
  configMapName: "theme-Hingle-configMap"
  version: 2.2.0
  requires: 2.0.0
  customTemplates:
    category:
      - name: 书影分类模板
        description: 书影等需要展示封面的分类展示
        screenshot:
        file: ./custom_pages/movie.html